### ISSUE TITLE
Can you release your augmented dataset?

### ISSUE THREAD

**Issue by RaymondJiangkw** [google/volux-gan#1]
Hi!

Thanks for your awesome work of enabling HDRI lighting manipulation in the facial NeRF! The design is really inspiring.

I observe that the lighting manipulation relies on the augmented dataset, which is generated by the Total Relighting according to the paper.

Since the Total Relighting is not open-source, I wonder whether it is possible to release your augmented dataset for boosting relevant studies?

Thanks in advance!

**Comment by feitongt** [comment]
Hi,

Thanks for being interested in our work. Due to license of the datasets and Total Relighting not being open-sourced by Google now, we cannot release the augmented dataset, but the Total Relighting is planned to be released. Please stay tuned.

Thanks,
