### ISSUE TITLE
How to rotate the environment map?

### ISSUE THREAD

**Issue by RaymondJiangkw** [google/volux-gan#2]
Hi, awesome work!

I have tried the notebook, but I wonder how to fix the pose while rotating the environment map?

I have tested:
- Horizontally or Vertically shifting the HDRI map as arrays.
- Rotating the HDRI map as arrays.
- Explicitly passing the `camera_orientation` to the `infer_relit`.

However, none of them give me the results shown in the project page which features the obvious moving shadow.

Thus, I wonder what's the correct way to rotate the environment map? Thanks!

**Comment by feitongt** [comment]
Hi,

Thanks for being interested in our work. We achieved the environment map rotating by horizontally shifting the HDRI maps as you mentioned. Sorry for being unclear, we just updated the notebook to support that.

Thanks,
